[env:m5stack-cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -Isrc/core
lib_deps =
  m5stack/M5Cardputer
  bblanchon/ArduinoJson@^7.0.4
  earlephilhower/ESP8266Audio@1.9.7
